//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MoonPad.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MoonPad.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;SyntaxLanguage Key=&quot;Lua&quot; LanguageDefinitionVersion=&quot;4.0&quot; Secure=&quot;True&quot;
        ///				SyntaxLanguageTypeName=&quot;MoonPad.LuaDynamicSyntaxLanguage, MoonPad&quot;
        ///				xmlns=&quot;http://ActiproSoftware/SyntaxEditor/4.0/LanguageDefinition&quot;&gt;
        ///
        ///	&lt;!-- String Properties --&gt;
        ///	&lt;Properties&gt;
        ///		&lt;Property Key=&quot;Creator&quot; Value=&quot;Actipro Software LLC&quot; /&gt;
        ///		&lt;Property Key=&quot;Copyright&quot; Value=&quot;Copyright (c) 2001-2009 Actipro Software LLC.  All rights reserved.&quot; /&gt;
        ///	&lt;/Properties&gt;
        ///
        ///	&lt;!-- Highlighting Styles --&gt;
        ///	&lt;Styles&gt;
        ///		&lt;Style Key=&quot;Reserve [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ActiproSoftware_Lua {
            get {
                return ResourceManager.GetString("ActiproSoftware_Lua", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string htdocs_index_html {
            get {
                return ResourceManager.GetString("htdocs_index_html", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] PragmataPro_Mono_R_0826 {
            get {
                object obj = ResourceManager.GetObject("PragmataPro_Mono_R_0826", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] PragmataPro_Mono_R_liga_0826 {
            get {
                object obj = ResourceManager.GetObject("PragmataPro_Mono_R_liga_0826", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] PragmataProR_0826 {
            get {
                object obj = ResourceManager.GetObject("PragmataProR_0826", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] PragmataProR_liga_0826 {
            get {
                object obj = ResourceManager.GetObject("PragmataProR_liga_0826", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ProFontWindows {
            get {
                object obj = ResourceManager.GetObject("ProFontWindows", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
